const bookingsTemplate = [
    "Excavator",
    "Retaining walls",
    "Site set out",
    "Plumber drainer",
    "Plumber rough in",
    "Plumber fit off",
    "Bobcat site clear",
    "Pier inspection",
    "Bobcat slab prep",
    "Concreter",
    "Termite protection",
    "Slab inspection",
    "Concrete pump",
    "Electrician U/Power",
    "Electrician rough in",
    "Electrician fit off",
    "Electrician AC",
    "Plasterer",
    "Crane truss lift",
    "Frame inspection",
    "Roofer",
    "Edge protection",
    "Carpenter frame",
    "Carpenter rough in",
    "Carpenter soffits",
    "Carpenter fix out",
    "Carpenter finish out",
    "Bricklayer",
    "Garage door",
    "Tiler",
    "Painter",
    "Concrete kerb cut",
    "Drive/concreter",
    "Dividing fencing",
    "Fencing",
    "Bobcat clean",
    "TV antenna",
    "Garden kerbing",
    "Insulation/ceiling",
    "Final inspection",
    "Cleaning",
    "Silicon sealer"
];

export default bookingsTemplate;