const bookingTemplate = [
    "Excavator",
    "Retaining walls",
    "Site set out",
    "Plumber drainer",
    "Plumber rough in",
    "Plumber fit off",
    "Bobcat",
    "Pier inspection",
    "Concreter",
    "Termite protection",
    "Slab inspection",
    "Concrete pump",
    "Electrician U/Power",
    "Electrician rough in",
    "Electrician fit off",
    "Electrician AC",
    "Crane truss lift",
    "Frame inspection",
    "Edge protection",
    "Carpenter frame",
    "Carpenter rough in",
    "Carpenter soffits",
    "Carpenter fix out",
    "Carpenter finish out",
    "Bricklayer",
    "Garage door",
    "Tiler",
    "Painter",
    "Concrete kerb cut",
    "Drive/concreter",
    "Dividing fencing",
    "Fencing",
    "Bobcat clean",
    "TV antenna",
    "Garden kerbing",
    "Insulation/ceiling",
    "Final inspection",
    "Cleaning",
    "Silicon sealer"
];

export default bookingTemplate;