const checklistTemplate = [
    "Retaining walls",
    "Crusher dust",
    "Concrete",
    "Steel/reo",
    "Pods",
    "WC hire",
    "Bolts tie down",
    "Frame and truss",
    "Gas fitter rough in",
    "Gas fitter fit off",
    "Phone rough in",
    "Hardware: rough in",
    "Hardware: fit off",
    "Hardware: FC",
    "Hardware: sink",
    "Hardware: PC",
    "Hardware: steel lintels",
    "Bricks",
    "Lights",
    "Water tank and pump",
    "Tiles",
    "Turf",
    "Landscaping",
    "Disconnect power",
    "Gas connection",
    "Oven",
    "Cooktop",
    "White goods",
    "Book gas fitter",
    "Hand over folder",
    "NBN connection",
    "Covenant bond refund"
];

export default checklistTemplate;